apiVersion: v1
kind: Service
metadata:
  name: average-db
  labels:
    app: average-db
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: average-db
