apiVersion: v1
kind: Service
metadata:
  name: complex-db-1
  labels:
    app: complex-db-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: complex-db-1
