apiVersion: v1
kind: Service
metadata:
  name: simlpe
  labels:
    app: simlpe
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: simlpe
